# Generated by Django 5.1.6 on 2025-02-23 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_alter_wishlistitem_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
