# Generated by Django 5.1.6 on 2025-02-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread', max_length=15),
        ),
    ]
