# Generated by Django 3.2.25 on 2025-02-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_created',
        ),
    ]
